# Generated by Django 5.2.9 on 2026-05-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_permissions_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constraintsnippet",
            name="body",
            field=models.JSONField(blank=True),
        ),
    ]
